// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package todos

import (
	"database/sql"
)

type Todo struct {
	ID          int32
	Task        sql.NullString
	CreatedBy   sql.NullInt64
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}
