// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package todos

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID          int32
	Task        sql.NullString
	CreatedBy   sql.NullInt64
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
	Done        sql.NullBool
}

type User struct {
	ID          int32
	Username    string
	EmailID     string
	PhoneNo     sql.NullString
	CreatedDate time.Time
	Password    string
}
